# Generated by Django 2.2.4 on 2025-06-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_day', models.DateField()),
                ('password', models.CharField(max_length=60)),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], default='child', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(upload_to='task_proofs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('child', models.ForeignKey(limit_choices_to={'role': 'child'}, on_delete=django.db.models.deletion.CASCADE, to='families_app.User')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families_app.Task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='families_app.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families_app.Family'),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('points_cost', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families_app.User')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families_app.Family')),
            ],
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(limit_choices_to={'role': 'child'}, on_delete=django.db.models.deletion.CASCADE, to='families_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families_app.Family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_families', to='families_app.User'),
        ),
        migrations.CreateModel(
            name='ClaimedReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(limit_choices_to={'role': 'child'}, on_delete=django.db.models.deletion.CASCADE, to='families_app.User')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families_app.Reward')),
            ],
        ),
    ]
