# Generated by Django 2.2.4 on 2025-06-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointstransaction',
            name='reason',
        ),
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rewards/'),
        ),
    ]
