# Generated by Django 2.2.4 on 2025-06-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0002_auto_20250626_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='point',
            field=models.IntegerField(default=10),
        ),
    ]
