# Generated by Django 2.2.4 on 2025-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0004_auto_20250627_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
