# Generated by Django 2.2.4 on 2025-06-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0005_auto_20250627_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimedreward',
            name='status',
        ),
    ]
