# Generated by Django 2.2.4 on 2025-06-27 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families_app', '0006_remove_claimedreward_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimedreward',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='families_app.Family'),
        ),
    ]
